name: Build

# TODO(milestone-5): Adapt to create app release on push to main
on:
  push:
    branches:
      - '*'

# https://github.com/electron-userland/electron-builder/issues/3179
env:
  USE_HARD_LINKS: false

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.19
          cache: npm

      - name: Install Yarn
        run: npm install --global yarn

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2

      - name: Bootstrap project
        run: yarn run bootstrap

      - name: Build desktop app
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn run build:desktop:all
