name: Build

# TODO(milestone-5): Adapt to create app release on push to main
on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.19
          cache: npm

      - name: Install Yarn
        run: npm install --global yarn

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2

      - name: Bootstrap project
        run: yarn run bootstrap

      - name: Build desktop app
        run: yarn run build:desktop:all
